TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'obisconcept.neoscookieconsent': true

ObisConcept:
  CookieConsent:
    enable: true
    includeJavaScript: true
    includeCss: true
    policyPageNode: ''
    translations:
      package: 'obisconcept.neoscookieconsent'
      source: 'Main'
    position: 'bottom'
    theme: 'block'
    palette:
      popup:
        background: '#000'
        text: '#fff'
      button:
        background: '#f1d600'
        text: '#000'
